USE [RDC_Dev]
GO

/****** Object:  Table [FORMULARIO].[CAMPO]    Script Date: 11/01/2018 11:33:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [FORMULARIO].[CAMPO](
	[CAMPO_ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDEM] [smallint] NOT NULL,
	[OBRIGATORIO] [bit] NOT NULL,
	[DESCRICAO] [nvarchar](max) NOT NULL,
	[SUB_CATEGORIA_ID] [int] NOT NULL,
	[TIPO_CAMPO_ID] [int] NOT NULL,
 CONSTRAINT [PK_FORMULARIO.CAMPO] PRIMARY KEY CLUSTERED 
(
	[CAMPO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [FORMULARIO].[CAMPO]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO.CAMPO_FORMULARIO.SUBCATEGORIA_SUB_CATEGORIA_ID] FOREIGN KEY([SUB_CATEGORIA_ID])
REFERENCES [FORMULARIO].[SUBCATEGORIA] ([SUB_CATEGORIA_ID])
GO

ALTER TABLE [FORMULARIO].[CAMPO] CHECK CONSTRAINT [FK_FORMULARIO.CAMPO_FORMULARIO.SUBCATEGORIA_SUB_CATEGORIA_ID]
GO

ALTER TABLE [FORMULARIO].[CAMPO]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO.CAMPO_FORMULARIO.TIPOCAMPO_TIPO_CAMPO_ID] FOREIGN KEY([TIPO_CAMPO_ID])
REFERENCES [FORMULARIO].[TIPOCAMPO] ([TIPO_CAMPO_ID])
GO

ALTER TABLE [FORMULARIO].[CAMPO] CHECK CONSTRAINT [FK_FORMULARIO.CAMPO_FORMULARIO.TIPOCAMPO_TIPO_CAMPO_ID]
GO


