USE [RDC_Dev]
GO

/****** Object:  Table [FORMULARIO].[SUBCATEGORIA]    Script Date: 11/01/2018 11:33:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [FORMULARIO].[SUBCATEGORIA](
	[SUB_CATEGORIA_ID] [int] IDENTITY(1,1) NOT NULL,
	[SLUG] [nvarchar](650) NOT NULL,
	[DESCRICAO] [nvarchar](300) NULL,
	[CATEGORIA_ID] [int] NOT NULL,
 CONSTRAINT [PK_FORMULARIO.SUBCATEGORIA] PRIMARY KEY CLUSTERED 
(
	[SUB_CATEGORIA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [FORMULARIO].[SUBCATEGORIA]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO.SUBCATEGORIA_FORMULARIO.CATEGORIA_CATEGORIA_ID] FOREIGN KEY([CATEGORIA_ID])
REFERENCES [FORMULARIO].[CATEGORIA] ([CATEGORIA_ID])
GO

ALTER TABLE [FORMULARIO].[SUBCATEGORIA] CHECK CONSTRAINT [FK_FORMULARIO.SUBCATEGORIA_FORMULARIO.CATEGORIA_CATEGORIA_ID]
GO


