USE [RDC_Dev]
GO

/****** Object:  Table [FORMULARIO].[TEXTOCAMPO]    Script Date: 11/01/2018 11:33:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [FORMULARIO].[TEXTOCAMPO](
	[TEXTO_CAMPO_ID] [int] IDENTITY(1,1) NOT NULL,
	[TEXTO] [nvarchar](max) NULL,
	[Valor] [nvarchar](max) NULL,
	[CAMPO_ID] [int] NOT NULL,
 CONSTRAINT [PK_FORMULARIO.TEXTOCAMPO] PRIMARY KEY CLUSTERED 
(
	[TEXTO_CAMPO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [FORMULARIO].[TEXTOCAMPO]  WITH CHECK ADD  CONSTRAINT [FK_FORMULARIO.TEXTOCAMPO_FORMULARIO.CAMPO_CAMPO_ID] FOREIGN KEY([CAMPO_ID])
REFERENCES [FORMULARIO].[CAMPO] ([CAMPO_ID])
GO

ALTER TABLE [FORMULARIO].[TEXTOCAMPO] CHECK CONSTRAINT [FK_FORMULARIO.TEXTOCAMPO_FORMULARIO.CAMPO_CAMPO_ID]
GO


