USE [RDC_Dev]
GO

/****** Object:  Table [FORMULARIO].[TIPOCAMPO]    Script Date: 11/01/2018 11:33:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [FORMULARIO].[TIPOCAMPO](
	[TIPO_CAMPO_ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [nvarchar](40) NOT NULL,
 CONSTRAINT [PK_FORMULARIO.TIPOCAMPO] PRIMARY KEY CLUSTERED 
(
	[TIPO_CAMPO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


